export type ErrorCode =
  | 'BAD_REQUEST'
  | 'UNAUTHORIZED'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'VALIDATION_ERROR'
  | 'TOO_MANY_REQUESTS'
  | 'INTERNAL_ERROR'
  | 'INVALID_CURSOR'
  | 'CARD_NOT_FOUND'
  | 'PRICE_NOT_FOUND'
  | 'SIGNALS_NOT_FOUND';
